accounts/urls.py
from django.urls import path
from django.views.generic import TemplateView

from accounts.views import LoginView, LogoutView, ProfileView, \
    ChangePasswordView, RecoverPasswordView, RecoveringPasswordView, \
    RegistrationView

app_name = 'accounts'
urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path(r'logout/', LogoutView.as_view(), name='logout'),
    path(r'profile/', ProfileView.as_view(), name='profile'),
    path(r'password/change/', ChangePasswordView.as_view(),
         name='change-password'),
    path(r'recover-password/', RecoverPasswordView.as_view(),
         name='recover_password'),
    path(r'recover-password-success/',
         TemplateView.as_view(
             template_name='accounts/recover_password_success.html'),
         name='recover_password_success'),
    path(r'recovering-password/<key>/',
         RecoveringPasswordView.as_view(), name='recovering_password'),
    path(r'recovering-password-success/',
         TemplateView.as_view(
             template_name='accounts/recovering_password_success.html'),
         name='recovering_password_success'),
    path(r'registration/', RegistrationView.as_view(), name='registration'),
    path(r'registration-success/c/',
         TemplateView.as_view(
             template_name='accounts/registratoin_success.html'),
         name='customer_registration_success'),
    path(r'registration-success/d/',
         TemplateView.as_view(
             template_name='accounts/registratoin_success.html'),
         name='developer_registration_success'),
]

azob/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView, TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('issues/', include('issues.urls', namespace='issues')),
    path('django/', include('landing.urls', namespace='landing')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^_nested_admin/', include('nested_admin.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    path('moderation/', TemplateView.as_view(
        template_name='on_moderation.html'), name='on_moderation'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += [
        path('404/', TemplateView.as_view(template_name='404.html'),name='p404')
    ]


urlpatterns += [
    url(r'^$',
        RedirectView.as_view(url='/issues/', permanent=False),
        name='index')
]

issues/urls.py
from django.urls import path

from . import views

app_name = 'issues'
urlpatterns = [
    path('', views.issue_list, name="issues"),
    # path('404/', views.p404, name="p404"),
    path('new-item/', views.new_item_html, name='issue_add_item'),
    path('new-block/<issue_id>/', views.new_block_html, name='issue_add_block'),
    path('comments/<issue_id>/', views.comments, name='comments'),
    path('files/<issue_id>/', views.files, name='files'),
    path('set-deadline/<issue_id>/', views.set_issue_deadline, name='set-deadline'),
    path('<project_id>/add/', views.add_issue, name='add_issue'),
    path('block/<issue_id>/<block_id>/', views.issue_block_developer, name='issue_block_developer'),
    path('block/<issue_id>/<block_id>/delete/', views.delete_estimate_block, name='delete-estimate-block'),
    path('status/<issue_id>/<revision>/<status>/', views.change_status, name='change-issue-status'),
    path('upload/<issue_id>/<project_id>/', views.upload_file, name='upload-file'),
    path('delete-file/<issue_id>/<file_id>/', views.delete_file, name='delete-file'),
    path('<id>/', views.issue, name='issue'),
]

accounts/forms.py
from django import forms
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.db.models import Q
from django.utils.safestring import mark_safe
from django.utils.translation import gettext as _

from accounts.models import Profile


class LoginForm(forms.Form):
    username = forms.CharField(
        label='',
        widget=forms.TextInput(
            attrs={'class': 'form-control',
                   'placeholder': _('Адрес электронной почты')}))
    password = forms.CharField(
        label='',
        widget=forms.PasswordInput(
            attrs={'class': 'form-control',
                   'placeholder': _('Пароль')}))

    def clean_username(self):
        return self.cleaned_data['username'].lower()

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username and password:
            user = authenticate(request=self.request, username=username,
                                password=password)
            if user is not None:
                if user.is_active:
                    login(self.request, user)
                else:
                    raise forms.ValidationError(
                        _('Данный пользователь неактивен'))
            else:
                raise forms.ValidationError(_('Неверные пароль или логин'))
        return self.cleaned_data


class ProfileForm(forms.ModelForm):
    password = forms.CharField(label='',
                               widget=forms.PasswordInput(
                                   {'placeholder': _('Введите свой пароль')}
                               ))
    email = forms.EmailField(label=_('Адрес электронной почты'))

    class Meta:
        model = Profile
        fields = ['name', 'email', 'password',
                  'do_not_notice_about_my_actions']

    def clean_password(self):
        password = self.cleaned_data['password']
        profile = self.instance
        if not profile.user.check_password(password):
            raise forms.ValidationError('Неверный пароль')
        return password

    def clean_email(self):
        email = self.cleaned_data['email']
        user = self.instance.user
        if User.objects.exclude(id=user.id).filter(email=email):
            raise forms.ValidationError(
                'Этот адрес электронной почты уже знят')
        return email

    def save(self, commit=True):
        profile = super().save(commit)
        user = profile.user
        user.email = self.cleaned_data['email']
        user.save()
        return profile


class ChangePasswordForm(forms.Form):
    password_old = forms.CharField(label='',
                                   widget=forms.PasswordInput(
                                       {'placeholder': _('Старый пароль')}
                                   ))
    password_new = forms.CharField(label='',
                                   widget=forms.PasswordInput(
                                       {'placeholder': _('Новый пароль')}
                                   ))
    password_new_1 = forms.CharField(label='',
                                     widget=forms.PasswordInput(
                                       {'placeholder':
                                            _('Подтверждение нового пароля')}
                                   ))

    def clean_password_old(self):
        passw = self.cleaned_data['password_old']
        if not self.request.user.check_password(passw):
            raise forms.ValidationError('Неверный пароль')
        return passw

    def clean(self):
        passw = self.cleaned_data['password_new']
        passw1 = self.cleaned_data['password_new_1']
        if passw != passw1:
            self.add_error('password_new_1', 'Два поля с паролями не совпадают')

        return self.cleaned_data


class RecoverPasswordForm(forms.Form):
    username = forms.CharField(label='',
                               widget=forms.TextInput(
                                   attrs={'class': 'form-control',
                                          'placeholder':
                                              _('Адрес электронной почты')}))

    def clean_username(self):
        username = self.cleaned_data.get('username')
        user = User.objects.filter(
            Q(username=username) | Q(email__iexact=username)).first()

        if user is None:
            raise forms.ValidationError(
                u'Пользователь с таким адресом электронной почты не найден')

        return user


class RecoveringPasswordForm(forms.Form):
    password = forms.CharField(label='',
                               widget=forms.PasswordInput(
                                   attrs={'class': 'form-control',
                                          'placeholder': _('Пароль')}))
    password2 = forms.CharField(label='',
                                widget=forms.PasswordInput(
                                    attrs={'class': 'form-control',
                                           'placeholder': _('Пароль ещё раз')
                                           }))

    def clean(self):
        pass1 = self.cleaned_data.get('password')
        pass2 = self.cleaned_data.get('password2')

        if pass1 != pass2:
            self.add_error('password2', _('Два поля с паролями не совпадают'))

        return self.cleaned_data


class RegistrationForm(forms.Form):
    type = forms.ChoiceField(
        label=_('Зарегистрироваться как:'),
        widget=forms.RadioSelect({'class': 'profile-type'}),
        choices=(
            (Profile.TYPE_CUSTOMER, _('Заказчик')),
            (Profile.TYPE_DEVELOPER, _('Разработчик')))
    )
    email = forms.EmailField(label='',
                             widget=forms.EmailInput(
                                 {'placeholder': _('Адрес электронной почты')}))
    name = forms.CharField(label='',
                           widget=forms.TextInput(
                               {'placeholder': _('Имя')}))
    password = forms.CharField(label='',
                               widget=forms.PasswordInput(
                                   {'placeholder': _('Пароль')}))
    password2 = forms.CharField(label='',
                                widget=forms.PasswordInput(
                                    {'placeholder': _('Пароль ещё раз')}))
    rules = forms.BooleanField(
        label=mark_safe(_('Я прочитал <a target="_blank" '
                          'href="/terms-and-conditions/">правила '
                          'использования</a> и согласен с ними')),
        required=False)

    def clean_rules(self):
        if not self.cleaned_data['rules']:
            raise forms.ValidationError(_('Необходимо прочитать и принять '
                                          'правила использования'))
        return self.cleaned_data

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email):
            raise forms.ValidationError(
                _('Этот адрес электронной почты уже знят'))
        return email

    def clean(self):
        pass1 = self.cleaned_data.get('password')
        pass2 = self.cleaned_data.get('password2')

        if pass1 != pass2:
            self.add_error('password2', _('Два поля с паролями не совпадают'))

        return self.cleaned_data

accounts/views.py
from datetime import datetime, timedelta

from django.conf import settings
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import redirect
from django.template.loader import render_to_string
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.utils.translation import gettext as _
from django.views.generic import FormView, TemplateView, UpdateView
from mailer import send_html_mail

from accounts.forms import *
from accounts.models import ResetPasswordRequest


class LoginView(FormView):
    form_class = LoginForm
    template_name = 'accounts/login.html'

    def get_success_url(self):
        return self.request.GET.get('next') or (
            None if self.request.is_ajax() else '/')

    def get_template_names(self):
        return 'accounts/login_ajax.html' if self.request.is_ajax() \
            else 'accounts/login.html'

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.request = self.request
        return form


class LogoutView(TemplateView):
    template_name = 'accounts/logout.html'

    def get(self, request, *args, **kwargs):
        logout(request)
        return super().get(request, *args, **kwargs)


@method_decorator(login_required, name='dispatch')
class ProfileView(UpdateView):
    form_class = ProfileForm
    template_name = 'accounts/profile.html'
    success_url = reverse_lazy('accounts:profile')

    def get_object(self, queryset=None):
        return self.request.user.profile

    def get_initial(self):
        initial = super().get_initial()
        initial.update({'email': self.request.user.email})
        return initial


@method_decorator(login_required, name='dispatch')
class ChangePasswordView(FormView):
    form_class = ChangePasswordForm
    template_name = 'accounts/change_password.html'
    success_url = reverse_lazy('accounts:profile')

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        # передадим request в форму чтобы в валидации проверить, правильность
        # пароля текущего пользователя
        form.request = self.request
        return form

    def form_valid(self, form):
        user = self.request.user
        user.set_password(form.cleaned_data['password_new'])
        user.save()
        login(self.request, user)
        return redirect(self.get_success_url())


class RecoverPasswordView(FormView):
    template_name = 'accounts/recover_password.html'
    form_class = RecoverPasswordForm

    def get_success_url(self):
        return reverse('accounts:recover_password_success')

    def form_valid(self, form):
        user = form.cleaned_data.get('username')
        key = ResetPasswordRequest.generate_key(user)
        url = reverse('accounts:recovering_password', args=[key])

        ctx_dict = {
            'url': 'http://{}{}'.format(settings.DOMAIN, url),
            'user': user,
        }
        send_html_mail(_('Сброс пароля на Azob.ru'),
                       render_to_string('accounts/emails/recover_password.txt',
                                        ctx_dict),
                       render_to_string('accounts/emails/recover_password.html',
                                        ctx_dict),
                       settings.DEFAULT_FROM_EMAIL,
                       [user.email],
                       priority="high")

        return super().form_valid(form)


class RecoveringPasswordView(FormView):
    template_name = 'accounts/recovering_password.html'
    password_request = None
    form_class = RecoveringPasswordForm

    def get_success_url(self):
        return reverse('accounts:recovering_password_success')

    def get_form(self, form_class=None):
        key = self.kwargs.get('key')
        r = ResetPasswordRequest.objects.filter(
            key__iexact=key,
            date__gt=datetime.now() - timedelta(days=1)).first()

        if r is None:
            raise Http404

        self.password_request = r
        return super().get_form(form_class)

    def form_valid(self, form):
        f = super().form_valid(form)
        self.password_request.user.set_password(
            form.cleaned_data.get('password'))
        self.password_request.user.save()
        self.password_request.delete()
        return f


class RegistrationView(FormView):
    template_name = 'accounts/registration.html'
    form_class = RegistrationForm

    def get_success_url(self):
        if self.request.user.profile.type == Profile.TYPE_CUSTOMER:
            return reverse('accounts:customer_registration_success')
        elif self.request.user.profile.type == Profile.TYPE_DEVELOPER:
            return reverse('accounts:developer_registration_success')

    def form_valid(self, form):
        user = User(
            email=form.cleaned_data.get('email'),
            username=form.cleaned_data.get('email'),
            is_active=True,
        )
        user.set_password(form.cleaned_data.get('password'))
        user.save()

        user.profile.name = form.cleaned_data.get('name')
        user.profile.type = form.cleaned_data.get('type')
        user.profile.save()

        login(self.request, user)

        send_html_mail(_('Добро пожаловать на сайт Azob.ru'),
                       render_to_string(
                           'accounts/emails/registration_success.txt'),
                       render_to_string(
                           'accounts/emails/registration_success.html'),
                       settings.DEFAULT_FROM_EMAIL,
                       [user.email],
                       priority="high")

        return super().form_valid(form)

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}

{% load bootstrap4 i18n %}

{% block title %}{% trans 'Измеить пароль' %}{% endblock %}

{% block container %}
    <main>

        <div class="container">
            <article class="row">
                <div class="offset-md-3 col-sm-6">

                    <h2>{% trans 'Изменить пароль' %}</h2>
                    <br/>

                    <form action="{% url 'accounts:change-password' %}" method="post" class="form" role="form">
                        {% csrf_token %}

                        {% bootstrap_form form %}

                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">{% trans 'Сохранить' %}</button>
                        </div>
                    </form>
                </div>
            </article>
        </div>
    </main>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% load bootstrap4 i18n %}

{% block title %}Вход на сайт{% endblock %}

{% block container %}
        <div class="container">
            <article class="row">
                <div class="offset-md-3 col-sm-6">
                    <h2>Войти на сайт</h2>
                    <br/>

                    <form action="{% url 'accounts:login' %}" method="post" class="form" role="form">
                        {% csrf_token %}

                        {% bootstrap_form form %}

                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">{% trans 'Log in' %}</button>
                            <a href="{% url 'accounts:registration' %}" class="btn btn-link">{% trans 'Регистрация' %}</a>
                            <a href="{% url 'accounts:recover_password' %}" class="btn btn-link">{% trans 'Забыли пароль?' %}</a>

{#            <a href="{% url 'auth_password_reset' %}" class="btn btn-link">{% trans 'Forgot password?' %}</a>#}
                        </div>
                    </form>
                </div>
            </article>
        </div>

{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'base.html' %}

{% block title %}Выход из сайта{% endblock %}

{% block container %}
    <main>
        <div class="container">
            <article class="row">
                <div class="col-md-12">
                    <h1>Вы завершили работу</h1>
                    <p>Возвращайтесь снова.</p>
                    <a href="{% url 'issues:issues' %}" class="btn btn-primary">Главная</a>
                    <a href="{% url 'accounts:login' %}" class="btn btn-outline-primary">Войти снова</a>
                </div>
            </article>
        </div>
    </main>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% load bootstrap4 i18n %}

{% block title %}{% trans 'Настройки' %}{% endblock %}

{% block container %}
    <main>
        <div class="container">
            <article class="row">
                <div class="offset-md-3 col-sm-6">

                    <form action="{% url 'accounts:profile' %}" method="post" class="form" role="form">
                        {% csrf_token %}

                        {% bootstrap_form form %}

                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">{% trans 'Сохранить' %}</button>
                            <a href="{% url 'accounts:change-password' %}" class="btn btn-link">{% trans 'Изменить пароль' %}</a>
                        </div>
                    </form>
                </div>
            </article>
        </div>
    </main>
{% endblock %}

accounts/templates/accounts/recover_password.html
{% extends 'base.html' %}

{% load bootstrap4 i18n %}

{% block title %}Сброс пароля{% endblock %}

{% block container %}
        <div class="container">
            <article class="row">
                <div class="offset-md-3 col-sm-6">

                    <h2>Сброс пароля</h2>
                    <br/>
                    <form method="post" class="form" role="form">
                        {% csrf_token %}

                        {% bootstrap_form form %}

                        <div class="form-group">
                        <button type="submit" class="btn btn-primary">{% trans 'Отправить' %}</button> &nbsp;

                        </div>
                    </form>
                </div>
            </article>
        </div>

{% endblock %}

accounts/templates/accounts/recover_password_success.html
{% extends 'base.html' %}

{% block title %}Выход из сайта{% endblock %}

{% block container %}
    <main>
        <div class="container">
            <article class="row">
                <div class="col-md-12">
                    <h2>Сброс пароля</h2>
                    <br/>
                    <p>Вам было отправлено письмо со ссылкой на сброс пароля. Проверьте вашу почту и перейдите по указанной ссылке для продолжения.</p>
                </div>
            </article>
        </div>
    </main>
{% endblock %}

accounts/templates/accounts/recovering_password.html
{% extends 'base.html' %}

{% load bootstrap4 i18n %}

{% block title %}Вход на сайт{% endblock %}

{% block container %}
        <div class="container">
            <article class="row">
                <div class="offset-md-3 col-sm-6">

                    <h2>Восстановление пароля</h2>
                    <br/>

                    <form method="post" class="form" role="form">
                        {% csrf_token %}

                        {% bootstrap_form form %}

                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">Задать пароль</button>
                        </div>
                    </form>
                </div>
            </article>
        </div>

{% endblock %}

accounts/templates/accounts/recovering_password_success.html
{% extends 'base.html' %}

{% load bootstrap4 i18n %}

{% block title %}Вход на сайт{% endblock %}


{% block container %}
    <main>
        <div class="container">
            <article class="row">
                <div class="offset-md-3 col-sm-6">
                    <h2>Восстановление пароля</h2>
                    <br/>
                    <p>Пароль изменен.</p>
                    <a href="{% url 'issues:issues' %}" class="btn btn-primary">Главная</a>
                    <a href="{% url 'accounts:login' %}" class="btn btn-outline-primary">Войти</a>
                </div>
            </article>
        </div>
    </main>
{% endblock %}

accounts/templates/accounts/registration.html
{% extends 'base.html' %}

{% load bootstrap4 i18n %}

{% block title %}Регистрация на Azob.ru{% endblock %}

{% block container %}
        <div class="container">
            <article class="row">
                <div class="offset-md-3 col-sm-6">
                    <h2>Регистрация на Azob.ru</h2>
                    <br/>

                    <form method="post" class="form registration-form" role="form">
                        {% csrf_token %}

                        {% bootstrap_form form %}

                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">{% trans 'Зарегистрироваться' %}</button>
                        </div>
                    </form>
                </div>
            </article>
        </div>

{% endblock %}

accounts/templates/accounts/registratoin_success.html
{% extends 'base.html' %}

{% load bootstrap4 i18n %}

{% block title %}Регистрация на Azob.ru{% endblock %}


{% block container %}
    <main>
        <div class="container">
            <article class="row">
                <div class="offset-md-3 col-sm-6">
                    <h2>Регистрация на Azob.ru</h2>
                    <br/>
                    <p>Вы успешно зарегистрировались на Azob.ru</p>
                    <br/>
                    <a href="{% url 'issues:issues' %}" class="btn btn-primary">Перейти в список проектов</a>
                </div>
            </article>
        </div>
    </main>
{% endblock %}