azob/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView, TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('issues/', include('issues.urls', namespace='issues')),
    path('django/', include('landing.urls', namespace='landing')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^_nested_admin/', include('nested_admin.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    path('moderation/', TemplateView.as_view(
        template_name='on_moderation.html'), name='on_moderation'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += [
        path('404/', TemplateView.as_view(template_name='404.html'),name='p404')
    ]


urlpatterns += [
    url(r'^$',
        RedirectView.as_view(url='/issues/', permanent=False),
        name='index')
]

issues/urls.py
from django.urls import path

from . import views

app_name = 'issues'
urlpatterns = [
    path('', views.issue_list, name="issues"),
    # path('404/', views.p404, name="p404"),
    path('new-item/', views.new_item_html, name='issue_add_item'),
    path('new-block/<issue_id>/', views.new_block_html, name='issue_add_block'),
    path('comments/<issue_id>/', views.comments, name='comments'),
    path('files/<issue_id>/', views.files, name='files'),
    path('set-deadline/<issue_id>/', views.set_issue_deadline, name='set-deadline'),
    path('<project_id>/add/', views.add_issue, name='add_issue'),
    path('block/<issue_id>/<block_id>/', views.issue_block_developer, name='issue_block_developer'),
    path('block/<issue_id>/<block_id>/delete/', views.delete_estimate_block, name='delete-estimate-block'),
    path('status/<issue_id>/<revision>/<status>/', views.change_status, name='change-issue-status'),
    path('upload/<issue_id>/<project_id>/', views.upload_file, name='upload-file'),
    path('delete-file/<issue_id>/<file_id>/', views.delete_file, name='delete-file'),
    path('<id>/', views.issue, name='issue'),
]

issues/forms.py
# from django import forms
from django.forms import ModelForm, formset_factory, CharField, TextInput, Textarea
# from tinymce.widgets import TinyMCE

from issues.models import Issue, File, Comment


class FileForm(ModelForm):
    class Meta:
        model = File
        fields = ['file']


FileFormSet = formset_factory(FileForm, extra=20)


class IssueForm(ModelForm):
    # description = forms.CharField(widget=TinyMCE(attrs={'cols': 80, 'rows': 7}))
    class Meta:
        model = Issue
        fields = ['title', 'description']


class EditorFieldWidget(Textarea):
    template_name = 'forms/widgets/editorfield.html'


class CommentForm(ModelForm):
    # text = forms.CharField(widget=TinyMCE(attrs={'cols': 80, 'rows': 6}))

    class Meta:
        model = Comment
        fields = ['text']
        widgets = {
            'text': EditorFieldWidget(attrs={'rows': 7, 'cols': False, 'placeholder': False})
        }
        labels = {
            'text': False
        }

issues/views.py
import uuid
from collections import defaultdict
from datetime import datetime

from django.conf import settings
from django.contrib.auth.decorators import user_passes_test, login_required
from django.db.models import Q
from django.http import HttpResponse, JsonResponse, Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse

from accounts.models import is_user_customer, is_user_developer
from accounts.moderated import moderation_required
from customers.models import Developer
from issues import mailer
from issues.forms import IssueForm, CommentForm
from issues.models import Issue, Block, Item, Comment, IssueStatus, File
from projects.models import Project, ProjectDeveloper


@login_required
@moderation_required
def issue_list(request):
    if is_user_developer(request.user):
        return developer_issue_list(request)
    if is_user_customer(request.user):
        return customer_issue_list(request)


@user_passes_test(is_user_customer)
def customer_issue_list(request):

    issues_qs = Issue.objects.select_related('project').filter(author=request.user.profile)
    issues_not_done_qs = issues_qs.exclude(status=IssueStatus.done)
    issues_done_qs = issues_qs.filter(status=IssueStatus.done)

    issues = defaultdict(list)
    projects_qs = Project.objects.filter(customer=request.user.profile.customer)
    for p in projects_qs:
        issues[p] = []

    for qs in [issues_not_done_qs, issues_done_qs]:
        for iss in qs:
            if request.user == iss.author.user:
                iss.has_comments = iss.has_unread_comments_from_developer()
            issues[iss.project].append(iss)

    issues_dict = list(issues.items())
    issues_dict.sort(key=lambda i: i[0].id)

    context = {
        'issues_dict': issues_dict,
        'profile': request.user.profile,
        'customer': request.user.profile.customer
    }

    return render(request, 'issue_list.html', context)


@user_passes_test(is_user_developer)
def developer_issue_list(request):

    profile = request.user.profile
    key_projects = ProjectDeveloper.objects.filter(user=profile,key=True).\
        values_list('project', flat=True)

    issues_qs = Issue.objects.select_related('project').filter(
        Q(developer=profile) | Q(project__id__in=key_projects)
    ).distinct()

    issues_not_done_qs = issues_qs.exclude(status=IssueStatus.done)
    issues_done_qs = issues_qs.filter(status=IssueStatus.done)

    issues = defaultdict(list)
    for qs in [issues_not_done_qs, issues_done_qs]:
        for iss in qs:
            if iss.developer and request.user == iss.developer.user:
                iss.has_comments = iss.has_unread_comments_from_customer()
            issues[iss.project].append(iss)

    issues_dict = list(issues.items())
    issues_dict.sort(key=lambda i: i[0].id)

    context = {
        'issues_dict': issues_dict,
        # 'issues_for_projects_dict': issues,
        'profile': profile,
        'customer': profile.customer
    }

    return render(request, 'issue_list.html', context)


@login_required
@moderation_required
def issue(request, id):
    try:
        id = int(id)
    except:
        raise Http404
    if is_user_developer(request.user):
        return developer_issue(request, id)
    if is_user_customer(request.user):
        return customer_issue(request, id)


@user_passes_test(is_user_customer)
def customer_issue(request, id):
    issue = get_object_or_404(Issue, id=id)
    if request.user != issue.author.user:
        raise Http404
    context = {
        'role': 'customer',
        'iss': issue,
        'profile': request.user.profile,
        'customer': request.user.profile.customer,
        'add_issue_url': reverse('issues:add_issue', args=(issue.project_id,)),
    }

    if request.user == issue.author.user:
        issue.mark_comments_from_developer_read()

    return render(request, 'issue_customer.html', context)


@user_passes_test(is_user_developer)
def developer_issue(request, id):
    issue = get_object_or_404(Issue, id=id)
    profile = request.user.profile
    if not request.user in issue.participants_users():
        raise Http404
    context = {
        'role': 'developer',
        'iss': issue,
        'profile': profile,
        'customer': issue.project.customer,
        'correction_coefficient': settings.CORRECTIONS_COEFFICIENT,
    }
    if profile in issue.project.responsible_developers():
        context['add_issue_url'] = reverse('issues:add_issue',
                                           args=(issue.project_id,))

    if issue.developer and request.user == issue.developer.user:
        issue.mark_comments_from_customer_read()
    return render(request, 'issue_developer.html', context)


@login_required
@moderation_required
def add_issue(request, project_id):
    project = get_object_or_404(Project, id=project_id)
    profile = request.user.profile

    if profile.customer != project.customer and not profile in project.responsible_developers():
        raise Http404

    try:
        developer = ProjectDeveloper.objects.filter(project=project, key=True).first().user
    except AttributeError:
        try:
            developer = Developer.objects.filter(customer=project.customer, key=True).first().user
        except:
            developer = None


    form = IssueForm(request.POST or None)

    if form.is_valid():

        author = profile
        if author.type == author.TYPE_DEVELOPER:
            author = project.default_author() or author

        issue = Issue.objects.create(
            project=project,
            title=form.cleaned_data['title'],
            description=form.cleaned_data['description'],
            author=author,
            developer=developer
        )

        for file_id in request.POST.getlist('fileIds[]'):
            if file_id:
                try:
                    file = File.objects.get(issue=None, id=file_id, author=profile)
                    file.issue = issue
                    file.save()
                except File.DoesNotExist:
                    pass

        mailer.add_issue(issue, request.get_host(), profile)

        return redirect('issues:issues')

    context = {
        'project': project,
        'form': form,
        'profile': profile,
        'customer': profile.customer,
        'add_issue_url': reverse('issues:add_issue', args=(project.id,)),
    }

    return render(request, 'add_issue.html', context)


@user_passes_test(is_user_developer)
@moderation_required
def issue_block_developer(request, issue_id, block_id):

    issue = get_object_or_404(Issue, id=issue_id, developer=request.user.profile)

    if block_id == '0':
        block = Block(issue=issue)
    else:
        block = get_object_or_404(Block, id=block_id, issue=issue)

    if request.POST:
        block.title = request.POST.get('title', '') or 'Доработка сайта'

        if not request.POST.get('cancel-editing'):
            block.description = request.POST.get('description', '') or ''
            block.save()

            for i in block.items.all():
                if request.POST.get('item-delete-{}'.format(i.id), 0) == '1':
                    i.delete()
                else:
                    i.title = request.POST.get('item-title-{}'.format(i.id), '')
                    try:
                        i.estimate = float(request.POST.get('item-estimate-{}'.format(i.id)).replace(',', '.'))
                    except ValueError:
                        i.estimate = 0
                    i.save()

            new_items_count = int(request.POST.get('new-items-count', 0))
            if new_items_count:
                try:
                    order = Item.objects.filter(block=block).latest('order').order + 1
                except Item.DoesNotExist:
                    order = 1

                for k in range(new_items_count):

                    if request.POST.get('new-item-delete-{}'.format(k), 0) == '1':
                        continue

                    i = Item(block=block, order=order+k)
                    i.title = request.POST.get('new-item-title-{}'.format(k), None)
                    try:
                        i.estimate = float(request.POST.get('new-item-estimate-{}'.format(k), '0.0').replace(',', '.'))
                    except ValueError:
                        i.estimate = 0

                    if i.title:
                        i.save()

    context = {
        'b': block,
        'iss': issue,
        'new_block': block_id == '0'
    }

    return render(request, 'issue_block_developer.html', context)


@user_passes_test(is_user_developer)
@moderation_required
def delete_estimate_block(request, issue_id, block_id):

    issue = get_object_or_404(Issue, id=issue_id, developer=request.user.profile)
    block = get_object_or_404(Block, id=block_id, issue=issue)

    block.delete()
    return HttpResponse('')


@user_passes_test(is_user_developer)
@moderation_required
def new_item_html(request):

    current_count = int(request.GET.get('current-count', 0))
    count = int(request.GET.get('count', 1))
    items = []
    for k in range(count):
        items.append(Item(id=current_count+k, estimate=''))

    block_id = request.GET.get('block-id')
    if block_id == '0':
        block = Block(id='0')
    else:
        block = get_object_or_404(Block, id=block_id)

    context = {
        'items': items,
        'b': block
    }
    return render(request, 'item_tpl.html', context)


@user_passes_test(is_user_developer)
@moderation_required
def new_block_html(request, issue_id):

    issue = get_object_or_404(Issue, id=issue_id, developer=request.user.profile)

    context = {
        'iss': issue,
        'uuid': uuid.uuid1()
    }
    return render(request, 'block_tpl.html', context)


@login_required
@moderation_required
def files(request, issue_id):
    issue = get_object_or_404(Issue, id=issue_id)
    context = {
        'iss': issue
    }
    return render(request, 'files.html', context)

issues/templates/add_issue.html
{% extends 'base.html' %}
{% load i18n %}
{% load bootstrap4 %}
{% load static %}
{% load thumbnail %}

{% block head %}
    <link rel="stylesheet" href="{% static 'simplemde/simplemde.min.css' %}">
{% endblock %}

{% block js_bottom %}
    {{ block.super }}

    <script src="{% static 'simplemde/simplemde.min.js' %}"></script>
    <script>
        var uploadUrl = "{% url 'issues:upload-file' 0 project.id %}";
        var addIssue = true;
    </script>
    <script src="{% static 'js/issue_files.js' %}?_=1703"></script>
    <script src="{% static 'js/markdown.js' %}?_=2703"></script>
{% endblock %}

{% block container %}

        <h2>{% trans 'Создание новой задачи для проекта' %} {{ project }}</h2>
        <form method="post" action="{% url 'issues:add_issue' project.id %}" enctype="multipart/form-data" id="new-issue-form">
            {% csrf_token %}
            <div class="form-group">
                {{ form.errors.title }}
                <input name="title" type="text" class="form-control" required="required">
            </div>
            <div class="form-group">
                <textarea name="description" class="form-control markdown" rows="7"></textarea>
            </div>
            <div id="file-upload">
                <button class="btn btn-primary btn-create-issue"
                        type="submit">{% trans 'Создать задачу' %}</button>
                {% csrf_token %}
                <label>
                    <input type="file" id="multiFiles" name="files[]" multiple="multiple">
                    <span class="issue-add-file-btn">Добавить файл</span>
                    <div class="loader"></div>
                </label>

            </div>
        </form>




{% endblock %}

issues/templates/attached_files.html
{% for f in files %}
    <div class="attached-file" data-file="{{ f.id }}">
        {{ f.filename }}
        <span class="delete-attached-file" href="{% url 'issues:delete-file' f.issue_id f.id %}"></span>
        <input type="hidden" name="fileIds[]" value="{{ f.id }}">
    </div>
{% endfor %}

issues/templates/issue.html
{% extends 'base.html' %}

{% load i18n %}
{% load thumbnail %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'simplemde/simplemde.min.css' %}">
{% endblock %}

{% block js_bottom %}
    {{ block.super }}
    <script src="{% static 'gijgo/gijgo.min.js' %}" type="text/javascript"></script>
    <link href="{% static 'gijgo/gijgo.min.css' %}" rel="stylesheet" type="text/css" />
    <script src="{% static 'gijgo/messages.ru-ru.js' %}" type="text/javascript"></script>
    <script>
        var commentsUrl = "{% url 'issues:comments' iss.id %}";
        var filesUrl = "{% url 'issues:files' iss.id %}";
        var statusUrl = "{% url 'issues:change-issue-status' iss.id iss.estimate_revision 'status-tpl' %}";
        var uploadUrl = "{% url 'issues:upload-file' iss.id iss.project_id %}";
        var setDeadlineUrl = "{% url 'issues:set-deadline' iss.id %}";
        var addIssue = false;
    </script>
    <script src="{% static 'js/issue_status.js' %}?_=1702"></script>
    <script src="{% static 'js/issue_files.js' %}?_=1703"></script>
    <script src="{% static 'simplemde/simplemde.min.js' %}"></script>
    <script src="{% static 'js/markdown.js' %}?_=2703"></script>
    <script src="{% static 'js/issue_set_deadline.js' %}?_=0102"></script>
    <script src="{% static 'js/issue_comments.js' %}?_=2803"></script>
{% endblock %}

{% block container %}

    <div class="modal fade" id="statusAlert" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">Modal title</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            ...
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-primary" data-dismiss="modal">{% trans 'Обновить' %}</button>
          </div>
        </div>
      </div>
    </div>

    <div class="modal fade" id="select-deadline-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">Укажите дату выполнения</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
              <div class="row">
                  <div class="col-3"></div>
                  <div class="col-6">
                      <input id="dedline-datepicker" />
                  </div>
              </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-primary btn-set-deadline">{% trans 'Сохранить' %}</button>
          </div>
        </div>
      </div>
    </div>

    <div class="header">
        <div class="row">
            <div class="col col-12 col-md-2 apply-work text-center d-md-none">
                {% include 'issue_status_action.html' %}
            </div>
            <div class="col">
                <div class="text task-name">
                    <a href="{% url 'issues:issues' %}"><span class="project-name">{{ iss.project.name }}</span></a>
                    <span class="arrow"></span>
                    <span class="number">#{{ iss.id }}</span>
                    <span class="name">{{ iss.title }}</span>
                    <span class="badge badge-primary total-customer-estimate">{{ iss.customer_estimate|floatformat:2 }} чч</span>
                    <span class="text">- оценка разработчиком</span>
                </div>
{#                <div class="user-info">#}
{#                        <div class="avatar">#}
{#                            {% thumbnail profile.avatar "90x90" crop="center" as im %}#}
{#                                <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">#}
{#                            {% empty %}#}
{#                                <img src="{% static 'images/avatar.svg' %}" width="200" height="200">#}
{#                            {% endthumbnail %}#}
{#                        </div>#}
{#                        <div class="text name">{{ profile.name }}</div>#}
{#                        <div class="text company">{{ customer }}</div>#}
{#                        {% if customer.site %}#}
{#                            <div class="text url">{% trans 'Веб-сайт' %}: <a href="{{ customer.site }}" class="no-transform">{{ customer.site }}</a></div>#}
{#                        {% endif %}#}
{#                    </div>#}
            </div>
{#            <div class="col">#}
{#                <div class="summary">#}
{#                    <div class="text">{% trans 'Оценка' %}: <span class="no-transform">{{ iss.customer_estimate }} {% trans 'чч' %}</span></div>#}
{#                    <div class="text">{% trans 'Дедлайн' %}: {{ iss.deadline|default_if_none:"" }}</div>#}
{#                    <div class="text">{% trans 'Готовность' %}: 17%</div>#}
{#                    <div class="text"><a href="" class="btn btn-primary no-transform">{% trans 'Принять работу' %}</a></div>#}
{#                </div>#}
{#            </div>#}
        </div>
        <div class="row">
            <div class="col col-12 col-md-10">
                <div class="badge badge-light info">
                    <div class="row">
                        <div class="col col-12 col-md-8">
                            {% if role == 'developer' %}
                                <span class="person">{{ iss.author.name }}</span>
                                <span class="developer"> - заказчик</span>
                                <span class="person">{{ iss.developer.name }}</span>
                                <span class="developer"> - разработчик</span>
                            {% else %}
                                <span class="person">{{ iss.developer.name }}</span>
                                <span class="developer"> - разработчик</span>
                            {% endif %}
                        </div>
                        <div class="col col-12 col-md-4 text-left text-md-right">
                            <span class="date">{{ iss.create_dt|date:"H:i / d b Y" }}</span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col col-12 col-md-2 apply-work text-center d-none d-md-block">
                {% include 'issue_status_action.html' %}
            </div>
        </div>

        {% if role == 'developer' and iss.is_status_in_process %}
            <div class="row deadline">
                <div class="col">
                    Планируемая дата выполнения:{% if iss.deadline %}
                    {{ iss.deadline|date:'d.m.Y' }}
                {% else %}
                    <a href="#select-deadline-modal" role="button" class="btn btn-primary" data-toggle="modal">{% trans 'Указать' %}</a>
                {% endif %}

                </div>
            </div>
        {% endif %}
        <div class="row">
            <div class="col task-description">{{ iss.html_description|safe|urlize}}</div>
        </div>
    </div>

{#    <div class="task-description">#}
{#        <ul class="nav nav-tabs buffer-top" id="task-tab" role="tablist">#}
{#            <li class="nav-item">#}
{#                <a class="nav-link active" id="description-tab" data-toggle="tab" href="#description" role="tab" aria-controls="home" aria-selected="true">{% trans 'Описание' %}</a>#}
{#            </li>#}
{#            <li class="nav-item">#}
{#                <a class="nav-link" id="estimation-tab" data-toggle="tab" href="#estimation" role="tab" aria-controls="profile" aria-selected="false">{% trans 'Оценка' %}</a>#}
{#            </li>#}
{#        </ul>#}


{#        <div class="tab-content" id="myTabContent">#}
{#            <div class="tab-pane fade show active" id="description" role="tabpanel" aria-labelledby="description-tab">#}
{#                <p class="description">#}
{#                    {{ iss.description|safe }}#}
{#                </p>#}
{#            </div>#}
{##}
{#            <div class="tab-pane fade" id="estimation" role="tabpanel" aria-labelledby="estimation-tab">#}
{#                {% block estimation %}{% endblock %}#}
{##}
{#            <p><b>Дополнительно:</b></p>#}
{#            <ul>#}
{#                <li>Все три версии вполне можно выводить одним и тем же HTML кодом на Bootstrap</li>#}
{#                <li>В ТЗ нет ничего о полях объектов недвижимости. Интересует не столько то, что выводится (прощадь, цена и т.п.), а георафические данные</li>#}
{#            </ul>#}
{##}
{##}
{#            </div>#}
{#        </div>#}

      <!--   <ul class="nav nav-tabs">
            <li class="nav-item"><a class="nav-link active" href="task-description-customer.html">Описание</a></li>
            <li class="nav-item"><a class="nav-link" href="task-estimation-customer.html">Оценка</a></li>
        </ul> -->

{##}


{#    </div>#}
    <div class="files-wrapper"></div>

    <div class="estimation">
        {% block estimation %}{% endblock %}
    </div>

    <div class="discussion">

    </div>

{% endblock %}

issues/templates/issue_developer.html
{% extends 'issue.html' %}

{% load i18n %}
{% load static %}

{% block js_bottom %}
    {{ block.super }}
    <script>
        var addItemUrl = "{% url 'issues:issue_add_item' %}";
        var addBlockUrl = "{% url 'issues:issue_add_block' iss.id %}";
        var DK = {{ iss.developer.developer_coefficient|stringformat:"f" }};
        var PK = {{ iss.project.project_coefficient|stringformat:"f" }};
        var CK = {{ iss.project.customer.customer_coefficient|stringformat:"f" }};
        var CorK = {{ correction_coefficient|stringformat:"f" }};
    </script>
    <script src="{% static 'js/issue_estimate.js' %}?_=0304"></script>
{% endblock %}

{% block estimation %}
    <div class="developer-estimation header">
        <a href="#">
            <div>Оценка времени разработчиком</div>
            <span>
                <span class="total-developer-estimate {% ifequal iss.developer_estimate 0 %}red{% endifequal %}">{{ iss.developer_estimate|floatformat:2 }}</span> {% trans 'чч' %}
            </span>
        </a>
    </div>

    <div class="modal fade bd-example-modal-sm" id="confirmDeleteBlockModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered modal-sm" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">{% trans 'Подтверждение удаления' %}</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            {% trans 'Удалить этот блок оценок?' %}
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-primary btn-cancel" data-dismiss="modal" data-confirm="cancel">{% trans 'Отмена' %}</button>
            <button type="button" class="btn btn-secondary btn-delete" data-dismiss="modal" data-confirm="confirm">{% trans 'Удалить' %}</button>
          </div>
        </div>
      </div>
    </div>

    {% for b in iss.blocks.all %}
        <div class="block block-{{ b.id }}">
            {% include 'issue_block_developer.html' %}
        </div>
    {% endfor %}

    {% if iss.is_status_wait_estimate %}
        <button class="btn btn-primary add-block">{% trans 'Добавить ещё блок' %}</button>
    {% endif %}

    <h5 class="buffer-top">{% trans 'ИТОГОВАЯ ОЦЕНКА' %}: <b class="total-estimate">{{ iss.estimate|floatformat:2 }}</b> {% trans 'чч' %}</h5>
    <h5 class="buffer-top">{% trans 'БУДЕТ ОПЛАЧЕНО' %}: <b class="total-developer-estimate gray">{{ iss.developer_estimate|floatformat:2 }}</b> {% trans 'чч' %}</h5>
    <h5 class="buffer-top">{% trans 'ВИДИТ ЗАКАЗЧИК' %}: <b class="total-customer-estimate">{{ iss.customer_estimate|floatformat:2 }}</b> {% trans 'чч' %}</h5>

{#                <div class="discussion">#}
{#                    <h6>Дополнительно:</h6>#}
{##}
{#                    <form>#}
{#                        <div class="btn-group mb-2" role="group" aria-label="Formatting">#}
{#                            <button type="button" class="btn"><b>Ж</b></button>#}
{#                            <button type="button" class="btn"><i>К</i></button>#}
{#                        </div>#}
{#                        <div class="form-group">#}
{#                            <textarea class="form-control" rows="7"></textarea>#}
{#                        </div>#}
{#                </div>#}

    {% if role == 'developer' %}
        <div class="row">
            {% if iss.is_status_wait_estimate %}

                <div class="col col-10 text-right send-estimation">
                    Итого, за выполнение этой задачи будет оплачено <b class="total-developer-estimate {% ifequal iss.customer_estimate 0 %}red{% endifequal %}">{{ iss.developer_estimate|floatformat:2 }}</b> чч &nbsp;&nbsp;&nbsp;&nbsp;
                </div>
                <div class="col col-2 text-center">
                    <button type="button"
                        data-status="send-estimate"
                        class="btn btn-primary btn-change-status">
                    {% trans 'Подтвердить' %}</button>
                </div>

            {% endif %}
            {% if iss.is_status_wait_estimate_approve %}
                <div class="col col-10 text-right send-estimation">
                    Оценка ожидает подтверждения со стороны Заказчика &nbsp;&nbsp;&nbsp;&nbsp;
                </div>
                <div class="col col-2 text-center">
                    <button type="button"
                            data-status="correct-estimate"
                            class="btn btn-outline-danger btn-change-status">
                        {% trans 'Исправить оценку' %}</button>
                </div>
            {% endif %}
            {% if iss.is_status_in_process %}
                <div class="col col-10 text-right send-estimation">
                    Оценка подтверждена Заказчиком, можно приступать к выполнению.
                </div>
            {% endif %}
            {% if iss.is_status_wait_fix_corrections %}
                <div class="col col-10 text-right send-estimation">
                    Необходимо исправить замечания
                </div>
            {% endif %}
        </div>

    {% endif %}

{% endblock %}