accounts/urls.py
from django.urls import path
from django.views.generic import TemplateView

from accounts.views import LoginView, LogoutView, ProfileView, \
    ChangePasswordView, RecoverPasswordView, RecoveringPasswordView, \
    RegistrationView

app_name = 'accounts'
urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path(r'logout/', LogoutView.as_view(), name='logout'),
    path(r'profile/', ProfileView.as_view(), name='profile'),
    path(r'password/change/', ChangePasswordView.as_view(),
         name='change-password'),
    path(r'recover-password/', RecoverPasswordView.as_view(),
         name='recover_password'),
    path(r'recover-password-success/',
         TemplateView.as_view(
             template_name='accounts/recover_password_success.html'),
         name='recover_password_success'),
    path(r'recovering-password/<key>/',
         RecoveringPasswordView.as_view(), name='recovering_password'),
    path(r'recovering-password-success/',
         TemplateView.as_view(
             template_name='accounts/recovering_password_success.html'),
         name='recovering_password_success'),
    path(r'registration/', RegistrationView.as_view(), name='registration'),
    path(r'registration-success/c/',
         TemplateView.as_view(
             template_name='accounts/registratoin_success.html'),
         name='customer_registration_success'),
    path(r'registration-success/d/',
         TemplateView.as_view(
             template_name='accounts/registratoin_success.html'),
         name='developer_registration_success'),
]

azob/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView, TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('issues/', include('issues.urls', namespace='issues')),
    path('django/', include('landing.urls', namespace='landing')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^_nested_admin/', include('nested_admin.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    path('moderation/', TemplateView.as_view(
        template_name='on_moderation.html'), name='on_moderation'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += [
        path('404/', TemplateView.as_view(template_name='404.html'),name='p404')
    ]


urlpatterns += [
    url(r'^$',
        RedirectView.as_view(url='/issues/', permanent=False),
        name='index')
]

issues/urls.py
from django.urls import path

from . import views

app_name = 'issues'
urlpatterns = [
    path('', views.issue_list, name="issues"),
    # path('404/', views.p404, name="p404"),
    path('new-item/', views.new_item_html, name='issue_add_item'),
    path('new-block/<issue_id>/', views.new_block_html, name='issue_add_block'),
    path('comments/<issue_id>/', views.comments, name='comments'),
    path('files/<issue_id>/', views.files, name='files'),
    path('set-deadline/<issue_id>/', views.set_issue_deadline, name='set-deadline'),
    path('<project_id>/add/', views.add_issue, name='add_issue'),
    path('block/<issue_id>/<block_id>/', views.issue_block_developer, name='issue_block_developer'),
    path('block/<issue_id>/<block_id>/delete/', views.delete_estimate_block, name='delete-estimate-block'),
    path('status/<issue_id>/<revision>/<status>/', views.change_status, name='change-issue-status'),
    path('upload/<issue_id>/<project_id>/', views.upload_file, name='upload-file'),
    path('delete-file/<issue_id>/<file_id>/', views.delete_file, name='delete-file'),
    path('<id>/', views.issue, name='issue'),
]

azob/forms.py
from django.forms import Textarea


class EditorFieldWidget(Textarea):
    template_name = 'forms/widgets/textarea.html'

azob/templates/base.html
<!doctype html>
{% load static i18n main_tags %}
{% get_counters as page_counters %}
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>{% block title %}AZOB.ru{% endblock %}</title>
    {% block head %}{% endblock %}
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
    {% for c in page_counters %}
        {{ c.header_code|safe }}
    {% endfor %}
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,400i,500,500i,700,700i,900,900i&amp;subset=cyrillic" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'scss/style.css' %}?_=0102">
    <link rel="stylesheet" href="{% static 'css/fonts.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}?_=0304">
    <link rel="stylesheet" href="{% static 'css/footer.css' %}">
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
</head>
<body>
    {% for c in page_counters %}
        {{ c.top_code|safe }}
    {% endfor %}
    <div class="container bg-light">
        <nav class="navbar navbar-expand-md navbar-light d-md-none row">
            {% if iss.project %}
                <div class="col col-12">
                    <div class="navbar-text project-name">
                        <a href="{% url 'issues:issues' %}">{{ iss.project.name }}</a>
                    </div>
                </div>
            {% endif %}

            <div class="col col-9">
                <a class="navbar-brand" href="/">
                    <img src="{% static 'images/logo.png' %}"/>
                </a>
                <div class="navbar-text username">
                    {% if request.user %}
                        <a href="{% url 'accounts:profile' %}">{{ request.user.profile.name }}</a>
                    {% endif %}
                </div>
            </div>
            <div class="col col-3 text-center">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
            <div class="col col-6">
                {% if customer %}
                    <div class="navbar-text balance">
                        {% trans 'Баланс' %}:  <b>{{ customer.hour_balance }} {% trans 'чч' %}</b>
                    </div>
                {% endif %}

            </div>
            <div class="col col-6 text-center">
                {% if add_issue_url %}
                    <button type="button" class="btn btn-primary btn-create" onclick='location="{{ add_issue_url }}"'>{% trans 'Создать задачу' %}</button>
                {% else %}
                    {% with request.user.profile.default_project as p %}
                        {% if p %}
                            <button type="button" class="btn btn-primary btn-create" onclick='location="{% url 'issues:add_issue' p.id %}"'>{% trans 'Создать задачу' %}</button>
                        {% endif %}
                    {% endwith %}
                {% endif %}
            </div>

            <div class="col col-12 text-center">
                <div class="collapse navbar-collapse" id="navbarsExampleDefault">
                    <ul class="navbar-nav ml-auto">
                        {% for item in menu_top %}
                            <li class="nav-item"><a class="nav-link" href="{{ item.url }}">{{ item.name }}</a></li>
                        {% endfor %}
                        {% if request.user.is_authenticated %}
                            <li class="nav-item"><a class="nav-link" href="{% url 'accounts:logout' %}">{% trans 'Выйти' %}</a></li>
                        {% else %}
                            <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}">{% trans 'Войти' %}</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>

        </nav>
        <nav class="navbar navbar-expand-md d-none d-md-flex">
            <a class="navbar-brand" href="/">
                <img src="{% static 'images/logo.png' %}"/>
            </a>

            <div class="navbar-text username">
                {% if request.user %}
                    <a href="{% url 'accounts:profile' %}">{{ request.user.profile.name }}</a>
                {% endif %}
            </div>

            {% if iss.project %}
                <div class="navbar-text project-name">
                    <a href="{% url 'issues:issues' %}">{{ iss.project.name }}</a>
                </div>
            {% endif %}

            {% if request.user.profile.customer %}
                <div class="navbar-text balance">
                    {% trans 'Баланс' %}:  <b>{{ request.user.profile.customer.hour_balance }} {% trans 'чч' %}</b>
                </div>
            {% endif %}

            {% if add_issue_url %}
                <button type="button" class="btn btn-primary btn-create" onclick='location="{{ add_issue_url }}"'>{% trans 'Создать задачу' %}</button>
            {% else %}
                {% with request.user.profile.default_project as p %}
                    {% if p %}
                        <button type="button" class="btn btn-primary btn-create" onclick='location="{% url 'issues:add_issue' p.id %}"'>{% trans 'Создать задачу' %}</button>
                    {% endif %}
                {% endwith %}
            {% endif %}



            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarsExampleDefault">

                <ul class="navbar-nav ml-auto">
                    {% for item in menu_top %}
                        <li class="nav-item"><a class="nav-link" href="{{ item.url }}">{{ item.name }}</a></li>
                    {% endfor %}
                    {% if request.user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'accounts:logout' %}">{% trans 'Выйти' %}</a></li>
                    {% else %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}">{% trans 'Войти' %}</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </div>

    <main role="main" class="container">

    {% block container %}{% endblock %}

    </main>

    <footer id="footer" class="footer"><!--Footer-->
        <div class="footer-bottom">
            <div class="container border-top">
                <div class="row">
                    <a class="navbar-brand" href="/">
                        <img src="{% static 'images/logo_in_time.png' %}"/>
                    </a>
                    <ul class="navbar">
                        {% for item in menu_bottom %}
                            <li class="nav-item"><a class="nav-link" href="{{ item.url }}">{{ item.name }}</a></li>
                        {% endfor %}

                        {% if request.user.is_authenticated %}
                            <li class="nav-item"><a class="nav-link" href="{% url 'accounts:logout' %}">{% trans 'Выйти' %}</a></li>
                        {% else %}
                            <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}">{% trans 'Войти' %}</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </footer>

    <script src="{% static 'js/jquery.form.min.js' %}"></script>

    {% block js_bottom %}{% endblock %}

    {% for c in page_counters %}
        {{ c.bottom_code|safe }}
    {% endfor %}
  </body>
</html>

azob/templates/on_moderation.html
{% extends '404.html' %}

{% load static i18n %}

{% block container %}
    <main role="main" class="container moderation">
        <div class="col-12 text-center d-none d-sm-block">
            <img src="{% static "images/moderation.png" %}">
        </div>
        <div class="col-12 text-center d-sm-none">
            <img src="{% static "images/moderationm.png" %}">
        </div>
        <div class="col-12 text-center not-found">
            <p>
                Ваша анкета находится на модерации <br/>
                <span>Мы уведомим Вас об окончании проверки</span>
            </p>
        </div>
        <div class="col-12 text-center">
            <button type="button" class="btn btn-primary" onclick='location="{% url 'accounts:profile' %}"'>{% trans 'В личный кабинет' %}</button>
        </div>
    </main>
{% endblock %}